Repository Arkantik/WildBook, pull requests merged in 2023-03, with the labels that each got.

#2 Top section mobile
  index.html
  src/assets/icons/connect.svg
  src/assets/icons/connected.svg
  src/assets/icons/filters.svg
  src/assets/icons/notif-bell.svg
  src/assets/icons/wcs-logo.svg
  src/assets/images/AnthonyGorski.png
  src/assets/images/EnzoCastagnos.jpeg
  src/assets/images/IntissarOthman.jpg
  src/assets/images/JFMorin.jpg
  src/assets/images/OyhanaMajhoubi.png
  src/assets/images/personal-PP.png
  src/assets/images/wcs-logo.png
  src/index.js
  src/style.css
Labels: Ready for merge

#9 Update of merged files
  index.html
  src/assets/icons/connectblack.svg
  src/assets/icons/message.svg
  src/assets/images/OyhanaMahjoubi.png
  src/assets/images/logo.png
  src/assets/images/logo2.png
  src/assets/intissar.jpeg
  src/index.js
  src/style.css
Labels: Bug

#11 Responsiveness fixed on the top section
  index.html
  src/assets/images/JeremyDohin.jpg
  src/index.js
  src/style.css
Labels: enhancement

#12 Wilders profiles
  .gitignore
  index.html
  src/style.css
Labels: 🌟 enhancement

#15 Version 1.0.0
  index.html
  src/index.js
  src/style.css
Labels: ✅ Ready for merge

#16 WildBook 1.0.0
  .gitignore
  README.md
  index.html
  src/assets/icons/connect.svg
  src/assets/icons/connectblack.svg
  src/assets/icons/connected.svg
  src/assets/icons/filters.svg
  src/assets/icons/message.svg
  src/assets/icons/notif-bell.svg
  src/assets/icons/wcs-logo.svg
  src/assets/images/AnthonyGorski.png
  src/assets/images/EnzoCastagnos.jpeg
  src/assets/images/IntissarOthman.jpg
  src/assets/images/JFMorin.jpg
  src/assets/images/JeremyDohin.jpg
  src/assets/images/OyhanaMahjoubi.png
  src/assets/images/kylian.png
  src/assets/images/logo.png
  src/assets/images/logo2.png
  src/assets/images/personal-PP.png
  src/assets/images/wcs-logo.png
  src/index.js
  src/style.css
Labels: ✅ Ready for merge
